src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderInviteResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/PractitionerResource.kt

The role name the UI will use to authenticate to the UI has been defined as ROLE_ESUPERVISION__ESUPERVISION_UI. Update the PreAuthorize role value on each affected route to use this value.

Update API authorisation role name

---

build.gradle.kts
docker-compose.yml
docs/http/full-invite-flow.http
docs/interactions.md
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/config/AwsConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/config/LocalAwsConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderInviteResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderInviteService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/invite/InviteInfo.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/PractitionerResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/S3UploadService.kt
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml
src/test/resources/application-test.yml

- Updates the flow to support the frontend's flow of uploading image as a separate step.
- The images are uploaded to S3 using pre-signed URLs. The frontend needs to request the URL by passing the invite uuid &  content type of the image (the frontend should have the content-type, and we don't want to deal with file extensions)
Note: all this currently works with localstack only.

Photo uploads using pre-signed S3 URLs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/App.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/invite/InviteInfo.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/PractitionerDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/PractitionerRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/PractitionerResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/PractitionerService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/ResourceDtos.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/offender/OffenderSetup.kt

Practitioner ids are defined by the ids on the user tokens returned by HMPPS auth. These are not necessarily valid UUIDs.
Change the type of the practitioner uuid field to String and update the related fields in various DTOs.

Change practitioner uuid type to string

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/config/RekogConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/ResourceDtos.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/S3UploadService.kt

- Requesting checkin upload locations can now return a collection of URLs. 
- we'll be using locations[0] as the upload location for the reference photo - not the cleanest, but properly shaping the API respose will have to wait
- adds an additional S3 service class to access the non MOJ resources used for the pilot

Use alternate S3 service for rekog, snapshot URL locations

---

docs/http/full-checkin-flow.http
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/ResourceDtos.kt

- Adds a `POST /{uuid}/auto_id_check` to update the checkin with rekognition face compare result.
- Adds a `POST /{uuid}/review`

Add endpoint to persist auto id check result

---

helm_deploy/values-dev.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/config/AppConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/config/NotificationsConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/config/NotifyConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/notifications/Contactable.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/notifications/GovNotifyNotificationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/notifications/Message.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/notifications/NotificationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/notifications/OffenderCheckinInviteMessage.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/notifications/PractitionerCheckinSubmittedMessage.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderSetupService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/PractitionerRepository.kt
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

Message templates have been added to the gov.uk notify configuration for checkin invite and submission messages. Add these to the app configuration(s) and remove the templates used for the old invite flow.
Add a Message interface type for messages which can be sent to a recipient. A recipient is a type which exposes a collection of contact methods (phone number or email). Implement the Contactable inteface for Offender and Practitioner types.
Add message types for the checkin invite and submission messages. These return a collection of named template parameters based on the message properties and application configuration. The application parameters are exposed via a new AppConfig class which is used to resolve references to checkins within the UI.
Update the NotificationService to send a …

Send messages on checkin invite and submission

---

src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/wiremock/HmppsAuthMockServer.kt
src/test/resources/application-test.yml

Use port 8091 for the mock HMPPS auth server in the tests so it differs from the port used by default in development. This means the tests can be run while the API is running in dev mode under the default configuration.

Change port for mock HMPPS auth server in tests

---

helm_deploy/hmpps-esupervision-api/values.yaml
src/main/resources/application.yml

The hmpps-esupervision-rekog-aws secret has been configured with the region and bucket name for rekognition in each enviornment. Load these from the environment in application.yml and configure then in the serivce environment within the helm service config.

Load AWS rekognition bucket name and region from secrets

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderEventLogDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderEventLogRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderEventLogService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/PractitionerDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/PractitionerRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/RequestValidation.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/OffenderCheckinTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/offender/SurveyTest.kt

Adds new endpoint `POST /offenders/:uuid/deactivate`. After calling that endpoint
- the offender's state is set to INACTIVE
- the offender's contact info is set to null
- the offender's first_checkin column is set to null
- any outstanding checkin records have status set to CANCELLED
- an entry in new table `offender_event_log` gets added, contains the reason for stopping the checkins provided by practitioner

API endpoint to stop checkins for an offender

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/jobs/CheckinNotifier.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/jobs/JobLog.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/jobs/JobLogDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/CheckinNotificationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderSetupService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/OffenderCheckinTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/jobs/CheckinNotifierTest.kt

Second piece of #47 
- adds `CheckinNotification` entity and repo - holds a record for each notification passed to GOV.UK Notify
- for notifications sent as part of a job, the `job` column will point to corresponding job log entry
- for on-off notification, the `reference` column should be used
- updates `CheckinNotifier` to process records in batches and insert `OffenderCheckin` records - this will allow us to find records for a job and request status from GOV.UK notify later, via `reference` col
Part of https://dsdmoj.atlassian.net/browse/ESUP-444

save metadata for notifications sent via a scheduled job

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/jobs/OffenderCheckinExpiryJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderService.kt
src/main/resources/application-dev.yml
src/main/resources/application.yml

Adds a cron job that goes marks checkins as expired. It uses existing configuration to determine the cutoff date.
The test schedule in application.yaml was updated to something more realistic.

cron job to mark checkins as expired

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinDto.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/NullResourceLocator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/ResourceLocator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/S3UploadService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/offender/SurveyTest.kt

Adds `snapshotUrl` property to the `OffenderCheckinDto` and a method to the `ResourceLocator` interface to populate that property.

Include snapshot URL in checkin response.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/NullResourceLocator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/ResourceLocator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/S3UploadService.kt

Adds an optional query param to `GET /offender_checkins/:uuid:?include-uploads=false`
which will force the response to include the video/snapshot URLs.

optionally force video/snapshot URLs when requesting checkin details

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/utils/S3UploadService.kt

We copy the snapshots from rekognition bucket to MOJ bucket since we don't want to mix them when using data just for display.

fix: correct location for video snapshot location

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderService.kt

- use `saveAndFlush` to ensure errors triggered immediately
- return a 4xx error when unique constraint violated (e.g. contact info already in use)

ESUP-521: offender update bug

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/jobs/CheckinNotifier.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/TestUtils.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/jobs/CheckinNotifierTest.kt

Fixes ESUP-607 - Prevent checkin invites being created before a PoP's first checkin date.
Fix calculation of checkin days based on the PoP first checkin date and interval. Period.toDays() returns only the residual number of days in the period, not the total number. So for example a 6-week period (42 days) is represented as 1 month and 11 days. The toDays() method returns 11 in this case, not 42 as required. Use LocalDate.until to get the total number of days between the first checkin date and job execution date.
Add tests for calculating checkin days to CheckinNotifierTest.

Fix checkin day calculation in invites job

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/offender/OffenderRepositoryTest.kt

This PR updates the query that produces a stream candidates for notifications and makes sure we skip those that already had a checkin created, submitted, reviewed, or cancelled.

ESUP-619: consider other checkin statuses when looking for notification candidates.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/notifications/PractitionerCheckinSubmittedMessage.kt

Count "NO_MATCH" or missing auto id check as a flag in practitioner email

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/jobs/CheckinNotificationStatusUpdater.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/jobs/CheckinNotifier.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/jobs/JobLog.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/jobs/OffenderCheckinExpiryJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/notifications/GovNotifyNotificationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/notifications/NotificationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/notifications/Referencable.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/CheckinNotificationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderCheckinService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/jobs/CheckinNotificationStatusUpdaterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/offender/OffenderRepositoryTest.kt

Modifies the notification status update job to also fetch the status for one off notifications. One off notifications are saved with a reference of 'CHK-YYYY-MM-dd' and we use that to fetch one-offs sent on a particular day. 
Also: save checkin notification in `createCheckin` when called with a 'single' notification context.

update notif. status updater job to include one-off notif. statuses

---

helm_deploy/hmpps-esupervision-api/values.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/config/PractitionerSiteConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/offender/OffenderRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/InMemoryPractitionerSiteRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/practitioner/PractitionerSiteRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/stats/StatsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/stats/StatsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/TestUtils.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/integration/stats/StatsServiceTest.kt

Issue ESUP-746 - Add StatsResource containing routes returning usage stats information.
Add query which fetches the number of PoPs actively registered for each practitioner in the system.
Add PractitionerSitesRepository which returns the named location for a practitioner if known. Add in-memory implementation which loads a mapping of username -> location name from a JSON string.
Add /stats/practitioner/registrations route which returns the number of PoP registrations for each practitioner along with their location if known.

Create controller for usage statistics

---

src/main/resources/application-dev.yml

Issue ESUP-790 - Remove the postgres data source and JPA configuration from the dev spring profile since this is identical to the config in the default profile.

Remove duplicate data access config from the dev profile

---

src/main/kotlin/uk/gov/justice/digital/hmpps/esupervisionapi/jobs/OffenderCheckinExpiryJob.kt
src/main/resources/application.yml

This PR modifies the checkin expiry job:
- narrows down the bounds for checkins considered for expiry
- adds logging to help find the bug
- adds a cache for practitioners (scoped to the duration of the job)

expiry job tweaks
